# Generated by Django 3.0.5 on 2020-05-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryplus', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='pics1'),
        ),
    ]
